src/CdiscountMarketPlaceApi_WebApp/Controllers/OfferManagerController.cs
using Microsoft.AspNetCore.Mvc;
using CdiscountMarketPlaceApi_WebApp.Models;
using CdiscountMarketPlaceApi_WebApp.Models.OfferManager;
using Microsoft.AspNetCore.Http;
using CdiscountMarketPlaceApi_WebApp.Enumeration;
using System;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CdiscountMarketPlaceApi_WebApp.Controllers
{
    public class OfferManagerController : Controller
    {
        // GET: /<controller>/
        const string SessionLogin = "_Login";
        const string SessionToken = "_Token";
        const string SessionEnvironment = "_Environment";

       // OfferManager _OfferManager;
        //Autentication _Autentication;
        /*public IActionResult Index()
        {
            _OfferManager = new OfferManager();
            return View(__OfferManager);
        }*/

        public IActionResult Welcome()
        {
            //ViewData["Message"] = "Hello " + name;
            //ViewData["NumTimes"] = numTimes;

            return View();
        }

        public void GetSessionData(ref Request MyRequest)
        {
            if (HttpContext.Session.GetString(SessionToken) != null)
            {
                MyRequest._Login = HttpContext.Session.GetString(SessionLogin);
                MyRequest._Token = HttpContext.Session.GetString(SessionToken);
                MyRequest._EnvironmentSelected = (EnvironmentEnum)Enum.Parse(typeof(EnvironmentEnum), HttpContext.Session.GetString(SessionEnvironment));
            }

        }
        public void SetSessionData(Request MyRequest)
        {
            if (MyRequest != null)
            {
                HttpContext.Session.SetString(SessionLogin, MyRequest._Login);
                HttpContext.Session.SetString(SessionToken, MyRequest._Autentication._Token);
                HttpContext.Session.SetString(SessionEnvironment, MyRequest._EnvironmentSelected.ToString());
            }
        }
        public ActionResult SubmitOfferPackageRequest()
        {
            Request MyRequest = new SubmitOfferPackageRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult SubmitOfferPackageMessage(SubmitOfferPackageRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new SubmitOfferPackageMessage(MyRequest));
        }
        public ActionResult GetOfferListPaginatedRequest()
        {
            Request MyRequest = new GetOfferListPaginatedRequest();
            if (HttpContext.Session.GetString(SessionToken) != null)
            {
                MyRequest._Login = HttpContext.Session.GetString(SessionLogin);
                MyRequest._Token = HttpContext.Session.GetString(SessionToken);
                MyRequest._EnvironmentSelected = (EnvironmentEnum)Enum.Parse(typeof(EnvironmentEnum), HttpContext.Session.GetString(SessionEnvironment));
            }
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult GetOfferListPaginatedMessage(GetOfferListPaginatedRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetOfferListPaginatedMessage(MyRequest));
        }
        public ActionResult GetOfferListRequest()
        {
            Request MyRequest = new GetOfferListRequest();
            if (HttpContext.Session.GetString(SessionToken) != null)
            {
                MyRequest._Login = HttpContext.Session.GetString(SessionLogin);
                MyRequest._Token = HttpContext.Session.GetString(SessionToken);
                MyRequest._EnvironmentSelected = (EnvironmentEnum)Enum.Parse(typeof(EnvironmentEnum), HttpContext.Session.GetString(SessionEnvironment));
            }
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult GetOfferListMessage(GetOfferListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetOfferListMessage(MyRequest));
        }

       
        public ActionResult GetOfferPackageSubmissionResultRequest()
        {
            Request MyRequest = new GetOfferPackageSubmissionResultRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }

        [HttpPost]
        public ActionResult GetOfferPackageSubmissionResultMessage(GetProductListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetOfferPackageSubmissionResultMessage(MyRequest));
        }

        
    }
}

src/CdiscountMarketPlaceApi_WebApp/Controllers/OrderManagerController.cs
using Microsoft.AspNetCore.Mvc;
using CdiscountMarketPlaceApi_WebApp.Models;
using CdiscountMarketPlaceApi_WebApp.Models.OrderManager;
using Microsoft.AspNetCore.Http;
using CdiscountMarketPlaceApi_WebApp.Enumeration;
using CdscntMkpApiReference_Prod;
using System.Linq;
using System;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CdiscountMarketPlaceApi_WebApp.Controllers
{
    public class OrderManagerController : Controller
    {
        // GET: /<controller>/
        const string SessionLogin = "_Login";
        const string SessionToken = "_Token";
        const string SessionEnvironment = "_Environment";

        // OfferManager _OfferManager;
        //Autentication _Autentication;
        /*public IActionResult Index()
        {
            _OfferManager = new OfferManager();
            return View(__OfferManager);
        }*/

        public IActionResult Welcome()
        {
            //ViewData["Message"] = "Hello " + name;
            //ViewData["NumTimes"] = numTimes;

            return View();
        }

        public void GetSessionData(ref Request MyRequest)
        {
            if (HttpContext.Session.GetString(SessionToken) != null)
            {
                MyRequest._Login = HttpContext.Session.GetString(SessionLogin);
                MyRequest._Token = HttpContext.Session.GetString(SessionToken);
                MyRequest._EnvironmentSelected = (EnvironmentEnum)Enum.Parse(typeof(EnvironmentEnum), HttpContext.Session.GetString(SessionEnvironment));
            }

        }
        public void SetSessionData(Request MyRequest)
        {
            if (MyRequest != null)
            {
                HttpContext.Session.SetString(SessionLogin, MyRequest._Login);
                HttpContext.Session.SetString(SessionToken, MyRequest._Autentication._Token);
                HttpContext.Session.SetString(SessionEnvironment, MyRequest._EnvironmentSelected.ToString());
            }
        }

        [HttpPost]
        public ActionResult ValidateOrderListRequest(GetOrderListMessage MyGetOrderListMessage)
        {
            Request MyRequest = new ValidateOrderListRequest(MyGetOrderListMessage);
            if (HttpContext.Session.GetString(SessionToken) != null)
            {
                MyRequest._Login = HttpContext.Session.GetString(SessionLogin);
                MyRequest._Token = HttpContext.Session.GetString(SessionToken);
                MyRequest._EnvironmentSelected = (EnvironmentEnum)Enum.Parse(typeof(EnvironmentEnum), HttpContext.Session.GetString(SessionEnvironment));
            }
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult ValidateOrderListResponse(ValidateOrderListRequest MyRequest)
        {
            foreach (ValidateOrder vo in MyRequest._ValidateOrderListMessage.OrderList)
            {
                vo.OrderLineList = vo.OrderLineList.Where(val => val.SellerProductId.Length > 0).ToArray();
            }
            
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new ValidateOrderListResponse(MyRequest));
        }

        public ActionResult GetOrderListRequest()
        {
            Request MyRequest = new GetOrderListRequest();
            if (HttpContext.Session.GetString(SessionToken) != null)
            {
                MyRequest._Login = HttpContext.Session.GetString(SessionLogin);
                MyRequest._Token = HttpContext.Session.GetString(SessionToken);
                MyRequest._EnvironmentSelected = (EnvironmentEnum)Enum.Parse(typeof(EnvironmentEnum), HttpContext.Session.GetString(SessionEnvironment));
            }
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult GetOrderListMessage(GetOrderListRequest MyRequest)
        {
          
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetOrderListMessage(MyRequest));
        }

    }
}

src/CdiscountMarketPlaceApi_WebApp/Controllers/ProductManagerController.cs
using Microsoft.AspNetCore.Mvc;
using CdiscountMarketPlaceApi_WebApp.Models;
using Microsoft.AspNetCore.Http;
using CdiscountMarketPlaceApi_WebApp.Enumeration;
using System;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace CdiscountMarketPlaceApi_WebApp.Controllers
{
    public class ProductManagerController : Controller
    {
        // GET: /<controller>/
        const string SessionLogin = "_Login";
        const string SessionToken = "_Token";
        const string SessionEnvironment = "_Environment";

       
        //Autentication _Autentication;
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Welcome()
        {
            //ViewData["Message"] = "Hello " + name;
            //ViewData["NumTimes"] = numTimes;

            return View();
        }

        public void GetSessionData(ref Request MyRequest)
        {
            if (HttpContext.Session.GetString(SessionToken) != null)
            {
                MyRequest._Login = HttpContext.Session.GetString(SessionLogin);
                MyRequest._Token = HttpContext.Session.GetString(SessionToken);
                MyRequest._EnvironmentSelected = (EnvironmentEnum)Enum.Parse(typeof(EnvironmentEnum),HttpContext.Session.GetString(SessionEnvironment));
            }           

        }
        public void SetSessionData(Request MyRequest)
        {
            if (MyRequest != null)
            {
                HttpContext.Session.SetString(SessionLogin, MyRequest._Login);
                HttpContext.Session.SetString(SessionToken, MyRequest._Autentication._Token);
                HttpContext.Session.SetString(SessionEnvironment, MyRequest._EnvironmentSelected.ToString());
            }
        }
        public ActionResult GetAllAllowedCategoryTreeRequest()
        {
            Request MyRequest = new GetAllAllowedCategoryTreeRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult GetAllAllowedCategoryTreeMessage(GetAllAllowedCategoryTreeRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetAllAllowedCategoryTreeMessage(MyRequest));          
        }
        public ActionResult GetAllowedCategoryTreeRequest()
        {
            Request MyRequest = new GetAllowedCategoryTreeRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }
        [HttpPost]
        public ActionResult GetAllowedCategoryTreeMessage(GetAllowedCategoryTreeRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetAllowedCategoryTreeMessage(MyRequest));
        }
        public ActionResult SubmitProductPackageRequest()
        {
            Request MyRequest = new SubmitProductPackageRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }
        
        [HttpPost]
        public ActionResult SubmitProductPackageMessage(SubmitProductPackageRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new SubmitProductPackageMessage(MyRequest));
        }

        public ActionResult GetProductListRequest()
        {
            Request MyRequest = new GetProductListRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }

        [HttpPost]
        public ActionResult GetProductListMessage(GetProductListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetProductListMessage(MyRequest));

        }

        public ActionResult GetProductListByIdentifierRequest()
        {
            Request MyRequest = new GetProductListByIdentifierRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);

        }

        [HttpPost]
        public ActionResult GetProductListByIdentifierMessage(GetProductListByIdentifierRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            //string Request.Form["UpdateMode"];
            return View(new GetProductListByIdentifierMessage(MyRequest));
        }

        public ActionResult GetProductPackageSubmissionResultRequest()
        {
            Request MyRequest = new GetProductPackageSubmissionResultRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }

        [HttpPost]
        public ActionResult GetProductPackageSubmissionResultMessage(GetProductListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetProductPackageSubmissionResultMessage(MyRequest));
        }

        public ActionResult GetBrandListRequest()
        {
            Request MyRequest = new GetBrandListRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
        }

        [HttpPost]
        public ActionResult GetBrandListMessage(GetBrandListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetBrandListMessage(MyRequest));
        }

        
         public  ActionResult GetAllModelListRequest() 
         {
            Request MyRequest = new GetAllModelListRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
          }
        [HttpPost]
        public ActionResult GetAllModelListMessage(GetBrandListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetAllModelListMessage(MyRequest));
        }
        /*public  ActionResult GetModelListRequest() 
         {
            Request MyRequest = new GetModelListRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
          }
        [HttpPost]
        public ActionResult GetModelListMessage(GetBrandListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetModelListMessage(MyRequest));
        }

        public ActionResult GetProductPackageMatchingFileDataRequest() 
         {
            Request MyRequest = new GetProductPackageMatchingFileDataRequest();
            GetSessionData(ref MyRequest);
            return View(MyRequest);
         }
        [HttpPost]
        public ActionResult GetProductPackageMatchingFileDataMessage(GetBrandListRequest MyRequest)
        {
            MyRequest.GetHeaderMessage();
            SetSessionData(MyRequest);
            return View(new GetProductPackageMatchingFileDataMessage(MyRequest));
        }*/
       
    }
}

src/CdiscountMarketPlaceApi_WebApp/Views/Shared/_Layout.cshtml
@using CdiscountMarketPlaceApi_WebApp.Enumeration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CdiscountMarketPlaceApi_WebApp</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="bower_components/angular-ui-tree/dist/angular-ui-tree.min.css">
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="bower_components/angular-ui-tree/dist/angular-ui-tree.min.css">
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Cdiscount Marketplace API WebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Product Manager<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("GetAllAllowedCategoryTree", "GetAllAllowedCategoryTreeRequest", "ProductManager")</li>                            
                            <li>@Html.ActionLink("SubmitProductPackage", "SubmitProductPackageRequest", "ProductManager")</li>
                            <li>@Html.ActionLink("GetAllowedCategoryTree", "GetAllowedCategoryTreeRequest", "ProductManager")</li>                            
                            <li>@Html.ActionLink("GetAllModelList", "GetAllModelListRequest", "ProductManager")</li>                            
                            <li>@Html.ActionLink("GetModelList", "GetModelListRequest", "ProductManager")</li>                            
                            <li>@Html.ActionLink("GetProductList", "GetProductListRequest", "ProductManager")</li>                            
                            <li>@Html.ActionLink("GetBrandList", "GetBrandListRequest", "ProductManager")</li>                            
                            <li>@Html.ActionLink("GetProductPackageSubmissionResult", "GetProductPackageSubmissionResultRequest", "ProductManager")</li>                            
                            <li>@Html.ActionLink("GetProductPackageMatchingFileData", "GetProductPackageMatchingFileDataRequest", "ProductManager")</li>                            
                            <li>@Html.ActionLink("GetProductListByIdentifier", "GetProductListByIdentifierRequest", "ProductManager")</li>

                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Offer manager<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("SubmitOfferPackage", "SubmitOfferPackageRequest", "OfferManager")</li>
                            <li>@Html.ActionLink("GetOfferPackageSubmissionResult", "GetOfferPackageSubmissionResultRequest", "OfferManager")</li>
                            <li>@Html.ActionLink("GetOfferList", "GetOfferListRequest", "OfferManager")</li>
                            <li>@Html.ActionLink("GetOfferListPaginated", "GetOfferListPaginatedRequest", "OfferManager")</li>                            
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Order manager<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("GetOrderList", "GetOrderListRequest", "OrderManager")</li>
                            <li>@Html.ActionLink("ValidateOrderList", "ValidateOrderListRequest", "OrderManager")</li>
                            <li>@Html.ActionLink("CreateRefundVoucher", "CreateRefundVoucherRequest", "OrderManager")</li>                 
                            <li>@Html.ActionLink("ManageParcel", "ManageParcelRequest", "OrderManager")</li>                 
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">CRM manager<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("GetOrderClaimList", "GetOrderClaimListRequest", "CRMManager")</li>
                            <li>@Html.ActionLink("GetOfferQuestionList", "GetOfferQuestionListRequest", "CRMManager")</li>
                            <li>@Html.ActionLink("CloseDiscussionList", "CloseDiscussionListRequest", "CRMManager")</li>
                            <li>@Html.ActionLink("GetDiscussionMailList", "GetDiscussionMailListRequest", "CRMManager")</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account manager<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("GetSellerInformation", "GetSellerInformationRequest", "AccountManager")</li>
                            <li>@Html.ActionLink("GetSellerIndicators", "GetSellerIndicatorsRequest", "AccountManager")</li>
                            <li>@Html.ActionLink("GetGlobalConfiguration", "GetGlobalConfigurationRequest", "AccountManager")</li>
                            <li>@Html.ActionLink("GetParcelShopList", "GetParcelShopListRequest", "AccountManager")</li>
                            <li>@Html.ActionLink("SubmitRelaysFile", "SubmitRelaysFileRequest", "AccountManager")</li>
                            <li>@Html.ActionLink("GetRelaysFileSubmissionResult", "GetRelaysFileSubmissionResultRequest", "AccountManager")</li>
                        </ul>
                    </li>
                </ul>               
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <br />
            <br />
            <p>&copy; 2017 - CdiscountMarketPlaceApi_WebApp</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/angular/angular.js"></script>
        <script type="text/javascript" src="bower_components/angular-ui-tree/dist/angular-ui-tree.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js"
                asp-fallback-src="~/lib/angular/angular.min.js"
                asp-fallback-test="window.angular">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script type="text/javascript" src="bower_components/angular-ui-tree/dist/angular-ui-tree.js"></script>
    </environment>

    @RenderSection("scripts", required: false)
    
</body>
</html>